### ISSUE TITLE
Files looks missing

### ISSUE THREAD

**Issue by pdeliot** [Drek282/PsychoStats#95] opened 2024-01-24 09:51 UTC
Hi,

Happy to see this project active.

I'm trying to setup a brand new PsychoStats server, but using the source code available today, installation is failing with some files missing.

For exemple: "go-dbinit.php"

**Comment by Rosenstein** [comment] 2024-01-24 10:03
Code base has been split into main repository and add-on repositories for each game that is supported.
![IMG_20240124_105957.jpg](https://github.com/Drek282/PsychoStats/assets/4959837/29f4b8d4-097b-416a-9936-12c6b309144c)

You will also need to download files from add-on repository for your game.

**Comment by pdeliot** [comment] 2024-01-24 18:15
Thank you,

This architecture do not allow to me to reach my target of one Psychostats for all games:-| .. But it does not really matter... ;-)

But I still unable to mate it work... 
stuck on :

`Warning: Undefined array key "source_content" in C:\Program Files\psychostats\www\includes\class_theme.php on line 761`

**Comment by Rosenstein** [comment] 2024-01-24 18:33
PS was not designed  to support multiple game mods in one installation.
You need to have separate folder and sql db for each game mod. One sql db could work, but there can be unforseen consequences. 

Tell us more about your host, PHP version

**Comment by Rosenstein** [comment] 2024-01-24 18:40
PS was not designed  to support multiple game mods in one installation.
You need to have separate folder and sql db for each game mod. One sql db could work, but there can be unforseen consequences. 

Tell us more about your host, PHP version, is it apache or something else.

Did you change default ACP settings?
This might be related to theme compilation settings.

**Comment by Drek282** [comment] 2024-01-24 19:24
Take a breath.  Delete all  your files.  Read the README and the INSTALL instructions.  Try again.

At a minimum before anyone here can help you you need to tell us what game and what mod you are using PS for.

**Comment by pdeliot** [comment] 2024-01-24 20:06
Hi Drek,

Thank you for your feedback.

I've done it several times.. and will try another time ;-)
I'm trying to reinstall my server that was working since 2009.

I'm now focused on [Counter-Strike: Source](https://github.com/Drek282/ps_cstrikes)...

But for my target I will need to find solutions for CS1.6, CS Source, CS GO and now CS2....
3.2.7 was able to handle more or less CS1.6, CS Source, CS GO. (if you need sample log files... I have some)...

Special point: I'm using Windows server.

**Comment by Drek282** [comment] 2024-01-24 20:16
I'm not talking about reinstalling your game server!

Just talking about deleting the PS files and trying again.

PS should be able to handle CS 1.6, CS Source, and maybe CS GO, although I don't know about that.

I'd love to have a batch of logs (several concurrent days please from a busy time period), for both CS GO and CS2.

You can email them to me at olstairs at rogers dot com

**Comment by Drek282** [comment] 2024-01-24 20:19
But @Rosenstein is correct.  PS doesn't handle multiple servers from the same install.  You will need to install PS for each game/mod and they will each need their own db.  However, you can install them in subfolders (one level only).

**Comment by Drek282** [comment] 2024-01-24 20:52
Yes, now we need to know what http server your host is using.

**Comment by Drek282** [comment] 2024-01-24 20:54
@pdeliot Did you disable theme compilation during install?

**Comment by pdeliot** [comment] 2024-01-24 21:25
Then, the issue was due to write protection on temporary folder...
Smarty was failing, even if cache is disabled (and should not use cache folder) ...

Now, perl script is failing due to this query:

`SELECT clanid,prevrank,rank,prevskill,skill,allowrank,lastdecay FROM ps_plr WHERE plrid=1`

"rank" is a reserved word and need to be quoted.

I've created the dabase from zero using the install process.
Maybe any quoting otpion is missing...

**Comment by Drek282** [comment] 2024-01-24 21:44
> Then, the issue was due to write protection on temporary folder... Smarty was failing, even if cache is disabled (and should not use cache folder) ...

Disabling theme compilation has not been tested.  That's now on the list

> Now, perl script is failing due to this query:
> 
> `SELECT clanid,prevrank,rank,prevskill,skill,allowrank,lastdecay FROM ps_plr WHERE plrid=1`
> 
> "rank" is a reserved word and need to be quoted.

I have installed PS, and run ./stats.pl hundreds of times, literally, and I've never experienced this error.  Can you please tell me which game and which mod you experienced this with?  Also, what version of Perl are you running?

**Comment by pdeliot** [comment] 2024-01-24 21:52
I'm focusing on [Counter-Strike: Source](https://github.com/Drek282/ps_cstrikes)...

Maybe a database option may change the behavior.

I'm using MySql 8.0.36 with all default settings.

**Comment by Drek282** [comment] 2024-01-24 23:09
What version of Perl are you using?

**Comment by Drek282** [comment] 2024-01-24 23:26
Ok, the problem is MySQL 8.  I will try quoting that word and see if that helps.  It may be a day or two before I get to this.

**Comment by Drek282** [comment] 2024-01-24 23:27
Most have moved from MySQL to MariaDB.

**Comment by Drek282** [comment] 2024-01-24 23:30
If you have that option I would suggest you switch to MariaDB.

**Comment by Drek282** [comment] 2024-01-24 23:44
Ok, after looking into this PsychoStats will not be supporting Oracle's versions of MySQL.  If you want to use PsychoStats you will need to switch to MariaDB.  I will be making that clear in the documentation.

**Comment by Drek282** [comment] 2024-01-25 00:17
But thank you @pdeliot, I wasn't aware of this issue.  I wasn't aware that anyone was even still using Oracle's versions of MySQL.

**Comment by Drek282** [comment] 2024-01-25 00:25
I'm closing this.  Please submit a new issue if you encounter more problems.

**Closed by Drek282** 2024-01-25 00:25 UTC

**Comment by Rosenstein** [comment] 2024-01-25 08:20
While I share opinion about Oracle's mysql with Drek, I will try and help you out.

Find this line in your preferred text/code editor >
https://github.com/Drek282/PsychoStats/blob/784e72d88c4b4f9bf947bcd0163c4f2e7e64060a/root/lib/PS/Player.pm#L389

And change it to >
```perl
	$self->{_plr} = $db->get_row_hash("SELECT clanid,prevrank,`rank`,prevskill,skill,allowrank,lastdecay " .
```
If that doesn't work (it probably will not since \` is special character in perl) change it to >
```perl
	$self->{_plr} = $db->get_row_hash("SELECT clanid,prevrank,\x60rank\x60,prevskill,skill,allowrank,lastdecay " .
```
You will need to do this wherever perl complains, and every time you overwrite perl scripts (which should be rare as these are not updated often).

**Comment by Drek282** [comment] 2024-01-25 11:25
It isn't just in the Perl backend, it will have to be done in the front end as well.  Switch to MariaDB...

**Comment by pdeliot** [comment] 2024-01-25 16:28
I have no much time to work on deployment for now.
I will go on later, but I'm facing PHP 8 comptabilities issues, then switching back to PHP 7, and other problems.

- "Ruffle" !?  problems.
- Country flags display issue (probably folder access rights problems).
- Cookies consent not working (always displayed).
- Live server connexion errors.

When I will have more time, I will troubleshoot that and open issues if required.

Thank you all...

**Comment by Drek282** [comment] 2024-01-25 16:33
Cookie consent always displays if cookies are not accepted.  You can entirely disable the cookie consent  in the ACP.

**Comment by Drek282** [comment] 2024-01-25 17:20
@pdeliot You also shouldn't be experiencing any issues with PHP 8.  My guess is your issues are with MySQL 8.  A lot of effort has gone into making this version of PS fully compatible with PHP 8—and I do mean a lot...

**Comment by pdeliot** [comment] 2024-01-25 17:30
> It isn't just in the Perl backend, it will have to be done in the front end as well. Switch to MariaDB...

Starting Mariadb  10.2.0, the 'rank' word is becoming reserved. and the same issue should occur (To be confirmed) :-(

**Comment by pdeliot** [comment] 2024-01-25 17:32
> @pdeliot You also shouldn't be experiencing any issues with PHP 8. My guess is your issues are with MySQL 8. A lot of effort has gone into making this version of PS fully compatible with PHP 8—and I do mean a lot...

For example, the player screen is failing in error with PHP 8.. switching back to PHP 7 allow it to be displayed gracefully :-|
I need time to dig deeper.

**Comment by pdeliot** [comment] 2024-01-25 17:41
> * "Ruffle" !?  problems.
> * Country flags display issue (probably folder access rights problems).
Solved! Mime types missing in web server configuration.

**Comment by Drek282** [comment] 2024-01-25 19:03
I'm using MariaDB version 10.11.4, and experiencing no issues with the word 'rank'.

I'm also running PHP 8.2.7 and experiencing no errors on the player pages.

It would be useful if you would post the error message you are getting.

**Comment by Drek282** [comment] 2024-01-25 19:09
If you are experiencing issues with PHP 8 you probably aren't running the latest version of PS available from this repo.  Did you in fact click on the "Code" button in the upper right and choose "Download as Zip"?  Is that the version of PS you are running?

**Comment by pdeliot** [comment] 2024-01-25 19:11
PHP 7.4.22
![image](https://github.com/Drek282/PsychoStats/assets/10339047/5eb3f9c2-ac94-441e-a2d7-a81b783af135)

PHP 8.3.2
![image](https://github.com/Drek282/PsychoStats/assets/10339047/f37caba1-efc0-4819-ba79-bdf45aa71fc3)

`Fatal error: Uncaught mysqli_sql_exception: Table 'psychostats.ps_c_plr_roles' doesn't exist in C:\Program Files\psychostats\www\includes\DB\mysql.php:105 Stack trace: #0 C:\Program Files\psychostats\www\includes\DB\mysql.php(105): mysqli_query() #1 C:\Program Files\psychostats\www\includes\DB\DB_PARENT.php(337): DB_mysql->query() #2 C:\Program Files\psychostats\www\player.php(105): DB_PARENT->column_exists() #3 {main} thrown in C:\Program Files\psychostats\www\includes\DB\mysql.php on line 105`

But I need more time to check if any php.ini parameter can also impact this.

**Comment by pdeliot** [comment] 2024-01-25 19:13
> If you are experiencing issues with PHP 8 you probably aren't running the latest version of PS available from this repo. Did you in fact click on the "Code" button in the upper right and choose "Download as Zip"? Is that the version of PS you are running?

Right...

**Comment by Drek282** [comment] 2024-01-25 19:59
No, check that.  That could well be related to running PHP 8.3.  I will have a look at that.

**Comment by Drek282** [comment] 2024-01-29 01:08
I have looked at the release notes for PHP 8.3, as well as various writeups.  I see nothing to indicate that mysqli would throw the error posted above.  I'm back to thinking this has to do with Oracle's MySQL 8.

Also, RANK() is a function in MariaDB, but the word "rank" is not reserved.

**Comment by Drek282** [comment] 2024-01-29 19:47
Ok, I've been able to replicate this issue.  It has been moved to the top of the priority list.  I'm going to start a new issue on it.

**Comment by Drek282** [comment] 2024-01-29 20:13
Thank you @pdeliot for the issues you reported here.  If there was some negativity in responding to this thread, it was rooted in the fact that the OP made it pretty clear that you had not read the README or the INSTALL files, which was a pretty rough basis on which to start a discussion.  The other issues with the reporting were that questions that were asked were not answered directly, and multiple issues were posted to the thread.

In future, please keep it to one issue per thread, and when one of us asks you what software you are using, and what versions, please respond directly and clearly with answers.

Not supporting MySQL 8 is a decision that was made as a result of this thread, and is certainly not your fault, but you will not receive any further support if you continue to use MySQL 8.
