### ISSUE TITLE
Installation Aborted!

### ISSUE THREAD

**Issue by bobl61** [Drek282/PsychoStats#76] opened 2023-04-15 21:58 UTC
I have tried installing PsychoStats 3.2.7b, but to no avail. The error message is: "Installation Aborted!
The installation was halted due to your session either timing out or another installation session was started! You must start over and try again. Be sure not to open a second installation window or it will fail again." I'm trying to install on a fully functional server: Xampp - Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.16. I have tried it on 2 different browsers (Edge and Chrome). I have cleared cookies. I have started the install process numerous times with the same result.

**Comment by Drek282** [comment] 2023-04-15 22:11
Please try 3.2.8b from the repo.  Top left "Code" link.  Click on "Code" in the upper right.  Choose "Download as Zip".

**Comment by bobl61** [comment] 2023-04-16 14:59
The installer will guide you through the setup process of installing PsychoStats 3.2.8b on your computer. Javascript and cookies must be enabled in your browser for the installer to work properly.
Installation Aborted!
The installation was halted due to your session either timing out or another installation session was started! You must start over and try again. Be sure not to open a second installation window or it will fail again.

**Comment by Drek282** [comment] 2023-04-16 15:42
What browser are  you using?  Can you do me a favour and try a different browser?  The other question I have is, are you hosting this on a domain, or an IP address?  That shouldn't make a difference, but you could try placing it in a subfolder (ie. [URL]/[folder]/).  I typically install in a subfolder and I have received reports of the  installation failing if it is in the domain root.

**Comment by bobl61** [comment] 2023-04-16 16:25
I tried on 2 browsers (Edge and Chrome). I have  Dynamic DNS pointing to the server. 
[http://psycho.servegame.com/](url) The upload dir is in a folder called stats. I have the root dir in the main xampp dir.

**Comment by Drek282** [comment] 2023-04-16 16:36
The contents of the "root" folder should be somewhere in a folder not accessible to the web.  The contents of the "www" folder should be either in the root folder accessed by the URL "http://psycho.servegame.com/" or in a subfolder in that root folder, example: "http://psycho.servegame.com/stats/".  Your use of the  word "upload" makes me wonder if you are actually using version 3.2.8b.  What used to be called "upload" is now the "www" folder.

Is there a chance that you've accidentally mixed the 3.2.8b files with an older version of PS?

**Comment by bobl61** [comment] 2023-04-16 16:50
I deleted all the old files before uploading 3.2.8b files. I tried installing without editing config.php and stats.php. I tried with adding the database info into config.php and stats.php.

![2023-04-16_124420](https://user-images.githubusercontent.com/107001969/232327790-06a635be-79ea-44a2-bc5f-568acb7fe82e.png)
![2023-04-16_124457](https://user-images.githubusercontent.com/107001969/232327795-bdc13ef0-6c2a-47b6-bd25-5b16d68fa8c6.png)

**Comment by Drek282** [comment] 2023-04-16 16:58
It looks like you haven't uploaded the game/mod specific files to your "www" folder.  Please read the INSTALL file, the version of that file included with 3.2.8b.  You are missing a lot of files in your "stats" folder.

**Comment by bobl61** [comment] 2023-04-16 17:12
All the files are there...
![2023-04-16_131203](https://user-images.githubusercontent.com/107001969/232329074-faca5c2f-1124-4391-aab2-35ccc7dad819.png)

**Comment by Drek282** [comment] 2023-04-16 18:31
Can you post the url you are using to access the stats please?

**Comment by Drek282** [comment] 2023-04-16 18:46
I think this is unrelated to your error, but there was an error in "install/mysql/defaults.sql".  You will need to download that file and replace the version you are  currently using.  This is in the main repo, not the game module repo.

Once that error was fixed I was able to successfully complete  the install.  But again, please post the full URL you are using to install your stats.

**Comment by bobl61** [comment] 2023-04-16 19:02
"http://psycho.servegame.com/stats/install/"

**Comment by Drek282** [comment] 2023-04-16 19:15
Ok, I've put in a call for some help on this.  I would ask one more thing.  If you aren't hosting anything else on that URL, can you please try moving PS to the root web folder (taking it out of stats), and try to run the install again.  I know the friend that was working with me on this experienced that same error.  He was also running XAMPP, but he had PS installed in the web root folder.

**Comment by Drek282** [comment] 2023-04-16 20:15
Ok, I think the problem is probably in your config.php.  Your config.php file should look as the following:

`<?php
$dbtype = 'mysql';
$dbhost = 'localhost';
$dbport = '';
$dbname = '[your database name]';
$dbuser = '[your database user]';
$dbpass = '[your database password]';
$dbtblprefix = 'ps_';
$site_url = '';
?>`

You need to create a database for PsychoStats *before* you run the install, the install will not do that for you.  You need to create a database user and grant that user full permissions on that database.  That database user also needs to have a password.

**Comment by Drek282** [comment] 2023-04-16 21:00
I've improved the error message to make it more specific and informative.  The file that has changed is "www/install/themes/default/index.html".

**Comment by Drek282** [comment] 2023-04-16 21:13
Having said that, even when I deleted the database I was unable to recreate the error.  But that may be because I am running on Linux, not Windows.

**Comment by bobl61** [comment] 2023-04-16 21:28
I moved all the files inside the web root folder. I updated the defaults.sql file and config.php. Same error. New install url "http://psycho.servegame.com/install/"

**Comment by Drek282** [comment] 2023-04-16 22:53
Did you create a specific database and user for PS, grant the permissions etc.?   It may be that  PS won't work with the MySQL super user.

**Comment by bobl61** [comment] 2023-04-16 23:29
I'll create a new user for PS and see if that works.

**Comment by Drek282** [comment] 2023-04-16 23:34
If these stats were going to be production, and not just for closed testing, you should never use the MySQL superuser, regardless.

**Comment by bobl61** [comment] 2023-04-17 00:54
Okay, I created a new user and gave database specific privileges to PS database. I edited config.php with new info and now I'm getting this: "Installation Aborted!
The most likely cause for this error is that you have not created a database and database user for PsychoStats and/or entered your database name, database username and database user password into the config.php file. You need to create a database and a database user, and give that user full permissions on that database. The other possible reason for this error is that your session either timed out or another installation session was started. If that was the case you must start over and try again. Make sure you start the installation from the beginning and do not use your back button to attemp to restart the installation. Make sure you do not open a second installation window or it will fail again."

**Comment by Drek282** [comment] 2023-04-17 01:07
Well, I'm stumped.  I don't know why you are getting that error, and I can't recreate it.  My guess is it has something to do with the way XAMPP does things, but I have no experience with XAMPP.  Or perhaps it's a Windows specific issue.  I'm sorry but I've shot my bolt.

**Comment by bobl61** [comment] 2023-04-17 01:12
I hear ya' bro. We gave it a shot.

**Comment by Rosenstein** [comment] 2023-04-18 22:05
```
Installation Aborted!
The installation was halted due to your session either timing out or another installation session was started! You must start over and try again. Be sure not to open a second installation window or it will fail again.
```
Error is displayed when you clear cookies during the installation.
Are you sure you have cookies enabled? Maybe you have system wide block on cookies, or perhaps some browser extension is blocking the cookie. Since Edge is now based on Chrome, I'm suspecting you have same extension in both browsers.
Try opening install folder from your mobile phone.

**Comment by bobl61** [comment] 2023-04-19 00:57
Tried installing it on my phone (android). Exact same error message. Not sure if this is related to the problem I'm having, but when I manually tried to import the database tables (default.sql)  I get this:
Error
MySQL said: Documentation
#1146 - Table 'psychostats3_1.ps_config' doesn't exist

If I use basic.sql it imports with no errors.
I also added my url to allow all cookies:
![2023-04-18_205634](https://user-images.githubusercontent.com/107001969/232938815-c2237a4d-1778-4577-bfe5-f78a38ce0fbc.png)

**Comment by Drek282** [comment] 2023-04-19 01:05
The PHP should do that for you.  You don't need to do that.  Again, I'm stumped, I have no idea, other than what I've already said, what is causing this error.

**Comment by bobl61** [comment] 2023-04-19 01:12
![giphy](https://user-images.githubusercontent.com/107001969/232941038-35dc175a-e559-4fc0-b2e9-b95e170ead6b.gif)

**Comment by Rosenstein** [comment] 2023-04-19 13:29
Did you change some settings in Apache/PHP configs?

**Comment by Rosenstein** [comment] 2023-04-19 16:25
And change this line https://github.com/Drek282/PsychoStats/blob/main/www/install/common.php#L32  to 
```
error_reporting(E_ALL); 
```

**Comment by bobl61** [comment] 2023-04-19 18:43
[psycho.servegame.com-error.log](https://github.com/Drek282/PsychoStats/files/11276563/psycho.servegame.com-error.log)

**Comment by Rosenstein** [comment] 2023-04-19 18:54
Is there anything in Apache logs?

**Comment by bobl61** [comment] 2023-04-19 19:01
[error.log](https://github.com/Drek282/PsychoStats/files/11276677/error.log)

**Comment by bobl61** [comment] 2023-04-19 19:02
I uploaded the install folder again and changed the common.php file.

**Comment by Rosenstein** [comment] 2023-04-19 19:35
You can edit comments and remove links for security, i will send logs to Drek.

**Comment by Drek282** [comment] 2023-04-19 19:39
I was so happy you were taking care of this...

I've downloaded the error.log.  :(

**Comment by Drek282** [comment] 2023-04-19 19:46
This is all through the logs:

`server certificate does NOT include an ID which matches the server name`

That might well be screwing up your session key, which would be the cause of that error.

**Comment by Rosenstein** [comment] 2023-04-19 19:47
We need to troubleshoot this further.
Follow this guide - https://medium.com/anditb/set-up-a-cookie-in-apache-with-php-43ff4437fc8a 
Step 2 and step 3, just so we can see if other scripts can create cookie. Create those files in "install" folder, so we can see if other script can create a cookie.

**Comment by bobl61** [comment] 2023-04-19 19:52
"http://psycho.servegame.com/install/coockieset.php"

**Comment by Drek282** [comment] 2023-04-19 19:54
I'm going to look at those PHP errors when I have a minute or two.  It might not be today.

**Comment by Rosenstein** [comment] 2023-04-19 19:57
> "http://psycho.servegame.com/install/coockieset.php"
> 
> "http://psycho.servegame.com/install/coockieset.html"

Change html to php

**Comment by bobl61** [comment] 2023-04-19 19:59
"http://psycho.servegame.com/install/coockieaccess.php"

**Comment by Drek282** [comment] 2023-04-20 17:58
Ok the first thing I saw when I looked at your php error.log was this:

`PHP Fatal error:  Uncaught Error: Call to undefined function set_magic_quotes_runtime() in C:\\xampp\\htdocs\\psycho.servegame.com\\stats\\install\\common.php:33\nStack trace:\n#0 C:\\xampp\\htdocs\\psycho.servegame.com\\stats\\install\\index.php(25): require_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\psycho.servegame.com\\stats\\install\\common.php on line 33`

That immediately tells me that you are not running the latest version, PsychoStats 3.2.8.b from the repo, because that line has been commented out in the latest PsychoStats.  In fact it is commented out in every version going back to 3.2.2b, the last version that Stormtrooper released back in 2008(?).  So I don't know what version of PsychoStats you are running @bobl61 but it isn't the latest version available from this repo.

Please follow these instructions.

1. Delete all the files and folders from your web folder and wherever you put the stats.pl script, except config.php.
2. Click on the "Code" link in the upper left of this repository.
3. Click on the green "Code" button in the upper right of that page.
4. Click on "Download Zip".
5. Extract the resulting file somewhere and follow the instructions in INSTALL.md, to the letter please, and try again.

**Comment by Drek282** [comment] 2023-04-20 18:23
Just to be sure I checked the second error in that file, and it also dates to version 3.2.2b.  So @bobl61 once you are actually running the latest 3.2.8b from this repository, please report back here.

**Comment by Drek282** [comment] 2023-04-20 18:39
I'm closing this for now.  This is clearly not a problem with 3.2.8b.  Please feel free report another issue if you still experience problems when you are using the latest version from this repository.

**Comment by huobage** [comment] 2023-06-02 04:28
I encountered the same error, also follow the tutorial steps to install is also a stop error
My system is centos7
The database configuration is set according to the process or the installation is terminated!
![屏幕截图 2023-06-02 122751](https://github.com/Drek282/PsychoStats/assets/120363621/3da620ca-d37e-4e7c-8f7a-c8e1d946e1f6)

**Comment by Rosenstein** [comment] 2023-06-02 04:45
https://github.com/Drek282/PsychoStats/blob/016876e6c12b439985767c6ec0a76260ff829b95/www/includes/class_session.php#L76
Change value to 0 as a temp fix.

**Comment by huobage** [comment] 2023-06-02 05:10
非常感谢，问题已解决！

**Comment by Drek282** [comment] 2023-06-02 11:05
@huobage Are you also using SSL?  Do you have a valid certificate for your domain?  Are you running the latest version from the repo—not 3.2.7b?

**Comment by huobage** [comment] 2023-06-02 11:13
@Drek282  I am using the latest 3.2.8b, the local LAN test environment, not using SSL.
I would like to ask a question, the background log FTP transmission method, how to fill in the path column.
![屏幕截图 2023-06-02 191221](https://github.com/Drek282/PsychoStats/assets/120363621/5e5252dc-9d3d-473f-b4ab-f224c6766444)

**Comment by Drek282** [comment] 2023-06-02 11:16
Log Path should be the path relative to your ftp root.

**Comment by Drek282** [comment] 2023-06-02 11:18
@huobage can you email me the url you are using to install your stats at olstairs at rogers dot com please?

**Comment by huobage** [comment] 2023-06-02 11:23
@Drek282 
I didn't fully understand what you meant, I used google translate.
My test environment is an internal network, do you need a url for intranet access?

**Comment by Drek282** [comment] 2023-06-02 11:26
Just send me the url you use to access your stats.  I'm not trying to access your stats, I just want to look at that url.

**Comment by Drek282** [comment] 2023-06-02 11:38
Can you try passive mode please?

**Comment by Drek282** [comment] 2023-06-02 11:39
I don't have much experience with the ftp functionality.  You could try just saving that as is and running stats.pl and see if it works.

**Comment by Drek282** [comment] 2023-06-02 11:50
I probably need to look at the code that tests the FTP.

**Comment by Drek282** [comment] 2023-06-02 12:43
@huobage if the root ftp folder contain the files the path needs to be "./"

**Comment by huobage** [comment] 2023-06-02 13:12
@Drek282  
Thank you very much, it has been read normally.
I've just started working on this newer version, used it around 2008.
Another question, how to change the display language of the webpage?

**Comment by Drek282** [comment] 2023-06-02 13:23
Unfortunately PS only currently supports en_US.  If you want it to support other languages you will have to add that support yourself.  That will not be a trivial undertaking.

**Comment by Rosenstein** [comment] 2023-06-02 14:17
> @Drek282 Thank you very much, it has been read normally. I've just started working on this newer version, used it around 2008. Another question, how to change the display language of the webpage?

If you need to translate PS to another language, make a copy of 'en_US.php' file and follow instructions at the top.
When you are done, copy that file to every theme, and new language should be available in dropdown in footer on main page.

https://github.com/Drek282/PsychoStats/blob/c0323d6f65d7cc10cd48964268a8709a5cba4e31/www/themes/default/language/en_US.php#L1-L15

**Comment by Drek282** [comment] 2023-06-02 14:54
If you do that, please submit that file to the repo.  We would *love* to have additional language support.

**Comment by Drek282** [comment] 2023-06-02 15:04
@huobage I have made some improvements to the log sources edit page when FTP/SFTP are chosen.  It is no longer necessary to re-enter a password every time a log source is tested, and './' is now automatically entered as a default path if the field is left empty.

**Comment by Drek282** [comment] 2023-06-02 15:08
@Rosenstein is going to add a conditional so that the secure cookie setting is only active if https is being used.

**Comment by huobage** [comment] 2023-06-02 15:10
@Drek282 
I'll test it out later,
I have always failed the SFTP test, and still prompts that the component is not installed.
The PHP extension ssh2 has been installed.

**Comment by Rosenstein** [comment] 2023-06-02 15:35
> @Drek282 
> I'll test it out later,
> I have always failed the SFTP test, and still prompts that the component is not installed.
> The PHP extension ssh2 has been installed.

It needs to be installed for PERL

**Comment by Drek282** [comment] 2023-06-02 20:39
I'm closing this issue.  Secure cookies are now only used if the host is using HTTPS.

**Closed by Drek282** 2023-06-02 20:39 UTC
